services:
  - type: web
    name: mizrahi-bot
    env: node
    plan: starter
    buildCommand: |
      apt-get update
      apt-get install -y wget curl gnupg2 ca-certificates fonts-liberation \
        libappindicator1 libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
        libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 \
        libnspr4 libnss3 libpango-1.0-0 libx11-6 libxcomposite1 libxdamage1 libxext6 \
        libxfixes3 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release xdg-utils libgbm-dev
      wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      dpkg -i google-chrome-stable_current_amd64.deb || apt-get -f install -y
      npm install
    startCommand: npm start
    envVars:
      - key: EMAIL_COMPONEY
        sync: false
      - key: EMAIL_PASS
        sync: false
