services:
  - type: worker
    name: mizrahi-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: EMAIL_COMPONEY
        value: yyooss552@email.com
      - key: EMAIL_PASS
        value: ctop hrhb abpx qnkf

